BoehmGC: fix an issue that gcc can't link libgc.a
```
/usr/bin/ld: /home/lemon/git/v/thirdparty/tcc/lib/libgc.a(gc.o): in function `GC_dlopen':
gc.c:(.text+0xd493): undefined reference to `dlopen'
collect2: error: ld returned 1 exit status
```
this happens due to the order of `-ldl` flags