comment out assert causing cgen error
/tmp/v/gen.13460345908576264927.tmp.c:7493:37: error: incompatible types when assigning to type ‘string {aka struct string}’ from type ‘v__token__Kind {aka enum <anonymous>}’
      v_assert_meta_info__t59.lvalue = (node->kind) /* typeof: v.ast.SelectorExpr type: 83 */ ;